name: Send mail
on: push

jobs: 
  mail:
    runs-on: ubuntu-latest
    
    steps:
    - name: Pring Hello world
      run: echo "Hello World"

    - name: Sending a mail
      if: $ {{ always() }}
  uses: josephsiga18/action-send-mail@v3
  with:
    
      server_address: smtp.gmail.com
      server: 465

      username: ${{ secrets.EMAIL_USERNAME }}
      password: ${{ secrets.EMAIL_PASSWORD }}
      
      subject: mail title.
      body: file://README.md
      contentType: text/html
      attachments: file://attachmets.json